version: "3.2"
services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    links:
      - database:databasex

  database:
    build:
      context: ./database/
      dockerfile: Dockerfile
    ports:
      - "8529:8529"
    environment:
      - ARANGO_NO_AUTH=1
