version: "3.2"
services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
    links:
      - db:db
    environment:
      WAIT_HOSTS: db:8529

  db:
    build:
      context: ./database/
      dockerfile: Dockerfile
    ports:
      - "8529:8529"

  webapp:
    build:
      context: ./webapp/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    links:
      - backend:backend
    depends_on:
      - backend
    environment:
      WAIT_HOSTS: backend:8888
